### ISSUE TITLE
Review Ticket 12/3

### ISSUE THREAD

**Issue by Pqhantom** [danaylevy2004/thesuperidolenthusiasts#12]

**Comment by jm1021** [comment]
Super Idol - Danilel. 4.8/5
* Nice wire, good intro. .9/1
* Technical data, api, visuals 1/1
* Management plan with Github and Deploy 2/2
* Progress leaving things in week they are done, action for 10-12 things in backlog.  .9/1

No  crossover scoring, no notes.  -1.  Quiz score will be looked up on CB
