### ISSUE TITLE
Review Ticket 12/10

### ISSUE THREAD

**Issue by danaylevy2004** [danaylevy2004/thesuperidolenthusiasts#24]
**Total Score:**

README quality, release day policies, Scrum Board to week after break
- [x] 1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: Readme is organized, everything is there: https://github.com/danaylevy2004/thesuperidolenthusiasts  

Deployed Web Site
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: Website is deployed and fully functional: http://cbrevamped.tk/ 

Create Task plan
- [ ]  1.0
- [x]  .75
- [ ]  .5
- [ ]  0
Justification: create task plan is completed, can be found on the wiki:  https://github.com/danaylevy2004/thesuperidolenthusiasts/wiki/Create-Task-Plan 

2.3 Extracting Information from Data, 2.4 Using Programs with Data
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: Completed and links to journals are on the readme

**Comment by Tigran7** [comment]
Individual- Tigran
About Page must Extend from Layout and have special customization (color pallet, background, etc)
- [ ]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: Page is extended and customized

Picture with Mask that toggles to Picture of Choice (ie pic without mask)
- [ ]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: Picture works and toggles correctly

Pull or show data (Web API) with information of interest
- [ ]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: API works

Establish link(s) to journal and other key indicators of your work and progress (remember pop quiz). TPT Link to Create Task planning
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: Links included

**Comment by Tigran7** [comment]
Individual- Daniel
About Page must Extend from Layout and have special customization (color pallet, background, etc)
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: Extends from layout and is customized

Picture with Mask that toggles to Picture of Choice (ie pic without mask)
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: Picture is working and toggles

Pull or show data (Web API) with information of interest
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: api works

Establish link(s) to journal and other key indicators of your work and progress (remember pop quiz). TPT Link to Create Task planning
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: Links to his journals

**Comment by DerekBokelman** [comment]
Individual- Derek
About Page must Extend from Layout and have special customization (color pallet, background, etc)
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: Page is customized and is extended from the layout

Picture with Mask that toggles to Picture of Choice (ie pic without mask)
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: Picture works when clicking the button

Pull or show data (Web API) with information of interest
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: Random joke teller works.

Establish link(s) to journal and other key indicators of your work and progress (remember pop quiz). TPT Link to Create Task planning
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: Links are within the page

**Comment by Pqhantom** [comment]
Individual- Matthew [proof](http://cbrevamped.tk/aboutmatt/)
About Page must Extend from Layout and have special customization (color pallet, background, etc)
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: there is a custom about me page that is being extended to the layout. 

Picture with Mask that toggles to Picture of Choice (ie pic without mask)
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: button that toggles the pictures

Pull or show data (Web API) with information of interest
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: simple rock paper scissors game :)

Establish link(s) to journal and other key indicators of your work and progress (remember pop quiz). TPT Link to Create Task planning
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: there is a temporary link on the page simply titled notes.

**Comment by Chom642** [comment]
Individual- Christopher (Proof: http://cbrevamped.tk/aboutchris/ )
About Page must Extend from Layout and have special customization (color pallet, background, etc)
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: Page is personalized and works

Picture with Mask that toggles to Picture of Choice (ie pic without mask)
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: toggle function works, and toggles between masked and unmasked picture

Pull or show data (Web API) with information of interest
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: API works, just not on school wifi

Establish link(s) to journal and other key indicators of your work and progress (remember pop quiz). TPT Link to Create Task planning
- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
Justification: Link leads to paired journal

**Comment by danaylevy2004** [comment]
Total score: 7.75/8
